import type { NextPage } from 'next';
import Head from 'next/head';
import ReactFullpage from '@fullpage/react-fullpage';
import Slide1 from './_slide1';
import Slide2 from './_slide2';
import Slide3 from './_slide3';
import Slide4 from './_slide4';

const API_KEY = process.env.API_KEY;

const Home: NextPage = (props: any) => {
  const slides = [Slide1, Slide2, Slide3, Slide4];
  return (
    <div>
      <Head>
        <title>Boda Javi & Patri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ReactFullpage
          licenseKey={'hejejdhsaks'}
          render={() => (
            <ReactFullpage.Wrapper>
              {slides.map((Slide, i) => (
                <section key={i} className="section">
                  <Slide apiKey={props.apiKey} />
                </section>
              ))}
            </ReactFullpage.Wrapper>
          )}
        />
      </main>

      <footer></footer>
    </div>
  );
};

Home.getInitialProps = async () => ({
  apiKey: API_KEY
});

export default Home;
